# Generated by Django 2.1.4 on 2019-11-07 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('gender', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('bio', models.TextField(null=True)),
                ('joined', models.DateField(default=datetime.datetime(2019, 11, 7, 12, 16, 47, 882383, tzinfo=utc))),
                ('avatar', models.TextField()),
                ('Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
