# Generated by Django 2.1.4 on 2019-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
