# Generated by Django 2.1.4 on 2019-11-07 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 7, 12, 17, 52, 590572, tzinfo=utc)),
        ),
    ]
