# Generated by Django 2.1.4 on 2019-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191210_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimage',
            name='image',
            field=models.ImageField(default='giphy.gif', upload_to=''),
        ),
    ]
