# Generated by Django 2.1.4 on 2019-11-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191116_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='friends',
            field=models.ManyToManyField(default=None, null=True, to='users.CustomerProfile'),
        ),
    ]
