# Generated by Django 2.1.4 on 2019-11-07 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191107_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='joined',
            field=models.DateField(default=datetime.datetime(2019, 11, 7, 12, 22, 6, 32196, tzinfo=utc)),
        ),
    ]
