# Generated by Django 2.1.4 on 2019-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191116_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='friends',
            field=models.ManyToManyField(to='users.CustomerProfile'),
        ),
    ]
