# Generated by Django 2.1.4 on 2019-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191107_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
