# Generated by Django 2.1.4 on 2019-12-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_1931'),
        ('users', '0004_auto_20191116_1036'),
    ]

    operations = [
    ]
