# Generated by Django 2.1.4 on 2019-11-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20191107_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(null=True)),
                ('active', models.BooleanField()),
                ('joined', models.DateField(auto_now_add=True)),
                ('Vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ven', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
