# Generated by Django 2.1.4 on 2019-11-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191111_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
