# Generated by Django 2.1.4 on 2019-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchimage',
            name='merch',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='images',
            field=models.ManyToManyField(to='merch.MerchImage'),
        ),
    ]
