# Generated by Django 2.1.4 on 2019-11-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20191114_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchuser',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
