# Generated by Django 2.1.4 on 2019-11-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_auto_20191112_0634'),
        ('merch', '0002_auto_20191111_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='game_id',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library.game'),
            preserve_default=False,
        ),
    ]
