# Generated by Django 2.1.4 on 2019-11-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_auto_20191116_1316'),
        ('merch', '0002_merchuser_transaction'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.game'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='images',
            field=models.ManyToManyField(to='merch.MerchImage'),
        ),
    ]
